# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
