# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161215_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 15, 20, 33, 44, 953190, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 15, 20, 34, 3, 850874, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
